name: Notificar Creación de Cliente
on: workflow_dispatch
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar al equipo
        run: echo "NUEVO CLIENTE CREADO: America Ruiz. Notificando al equipo: JeesusA, Ana-García, Carlos-López."